name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Check format
        run: |
          pnpm run format
          if [ -n "$(git status --porcelain)" ]; then
            echo 'Code is not formatted. Please run pnpm run format.'
            git --no-pager diff
            exit 1
          fi
      - name: Build
        run: pnpm run build:cli
